name: lint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test_pull_request:
    runs-on: ubuntu-20.04
    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v3

      # https://github.com/actions/setup-node
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Lint
        run: |
          npm ci
          npm run lint
          npm run build
